#!/usr/bin/env python3
"""Generate glyph_data.py — SVG path outlines for astrological glyphs.

Astrology wheels rendered with librsvg (GTK's Gdk.Texture) fail to rasterize
some glyphs from an embedded @font-face and silently fall back to Noto Color
Emoji (colored backgrounds / missing signs). Inline SVG <path> outlines are
immune to font fallback, so we precompute the outlines here.

Run with a Python that has fontTools:

    /usr/bin/python3 scripts/generate_glyph_paths.py

Output: src/astro_display/glyph_data.py (a plain data module with NO runtime
fontTools dependency). Re-run whenever LiberZodiac is rebuilt.
"""
import os
import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

FONT = Path.home() / ".local" / "share" / "fonts" / "LiberZodiac-Regular.ttf"
OUT = Path(__file__).resolve().parent.parent / "src" / "astro_display" / "glyph_data.py"
UPM = 2048  # Liberation Sans UPM

# name -> (codepoint, category)
GLYPHS = {
    # zodiac
    "Aries": (0x2648, "sign"), "Taurus": (0x2649, "sign"),
    "Gemini": (0x264A, "sign"), "Cancer": (0x264B, "sign"),
    "Leo": (0x264C, "sign"), "Virgo": (0x264D, "sign"),
    "Libra": (0x264E, "sign"), "Scorpio": (0x264F, "sign"),
    "Sagittarius": (0x2650, "sign"), "Capricorn": (0x2651, "sign"),
    "Aquarius": (0x2652, "sign"), "Pisces": (0x2653, "sign"),
    # bodies / luminaries
    "Sun": (0x2609, "body"), "Moon": (0x263D, "body"),
    "Mercury": (0x263F, "body"), "Venus": (0x2640, "body"),
    "Mars": (0x2642, "body"), "Jupiter": (0x2643, "body"),
    "Saturn": (0x2644, "body"), "Uranus": (0x2645, "body"),
    "Neptune": (0x2646, "body"), "Pluto": (0x2647, "body"),
    "Mean Node": (0x260A, "node"), "True Node": (0x260A, "node"),
    "South Node": (0x260B, "node"), "Chiron": (0x26B7, "body"),
    "Lilith": (0x26B8, "body"),
}


def main() -> int:
    if not FONT.exists():
        print(f"ERROR: font not found: {FONT}", file=sys.stderr)
        return 1
    font = TTFont(str(FONT))
    cmap = font.getBestCmap()
    glyphset = font.getGlyphSet()

    entries = []
    missing = []
    for name, (cp, cat) in GLYPHS.items():
        gname = cmap.get(cp)
        if gname is None or gname not in glyphset:
            missing.append(f"{name} (U+{cp:04X})")
            continue
        pen = SVGPathPen(glyphset)
        glyphset[gname].draw(pen)
        path = pen.getCommands()
        bpen = BoundsPen(glyphset)
        glyphset[gname].draw(bpen)
        (x0, y0, x1, y1) = bpen.bounds
        entries.append({
            "name": name,
            "cp": cp,
            "cat": cat,
            "path": path,
            "cx": round((x0 + x1) / 2.0, 2),
            "cy": round((y0 + y1) / 2.0, 2),
            "w": round(x1 - x0, 2),
            "h": round(y1 - y0, 2),
        })

    if missing:
        print("WARNING: glyphs not found in font:", ", ".join(missing), file=sys.stderr)

    lines = [
        '"""glyph_data.py — precomputed SVG path outlines for astrological glyphs.',
        "",
        "Generated by scripts/generate_glyph_paths.py from LiberZodiac-Regular.ttf.",
        "No runtime fontTools dependency. Paths are in font units (UPM 2048),",
        "y-up; renderers flip y and scale when embedding.",
        "",
        "GLOBAL_SIGNS and GLOBAL_BODIES map canonical name -> dict with keys:",
        "path, cx, cy, w, h. cx/cy are the outline center in font units.",
        '"""',
        "",
        f"UPM = {UPM}",
        "",
        "SIGNS = {",
    ]
    for e in entries:
        if e["cat"] == "sign":
            lines.append(f'    "{e["name"]}": {{"path": {e["path"]!r}, "cx": {e["cx"]}, "cy": {e["cy"]}, "w": {e["w"]}, "h": {e["h"]}}},')
    lines.append("}")
    lines.append("")
    lines.append("BODIES = {")
    for e in entries:
        if e["cat"] in ("body", "node"):
            lines.append(f'    "{e["name"]}": {{"path": {e["path"]!r}, "cx": {e["cx"]}, "cy": {e["cy"]}, "w": {e["w"]}, "h": {e["h"]}}},')
    lines.append("}")
    lines.append("")
    lines.append("ALL = {**SIGNS, **BODIES}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(entries)} glyphs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
